apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e2e-tests-go-sznpfgki-import-ci
  namespace: tssc-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/e2e-tests-go-sznpfgki-import/overlays/ci
    repoURL: https://github.com/rhtap-test-organization-jk/e2e-tests-go-sznpfgki-import-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-app-ci
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: tssc-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
